import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

const tmdbApiKey = process.env.REACT_APP_TMDB_KEY;

export const tmdbApi = createApi({
  reducerPath: "tmdbApi",
  baseQuery: fetchBaseQuery({ baseUrl: "https://api.themoviedb.org/3" }),
  endpoints: (builder) => ({
    // * Get Genres
    getGenres: builder.query({
      query: () => `genre/movie/list?api_key=${tmdbApiKey}`,
    }),

    // * Get Movies by [type]
    getMovies: builder.query({
      query: ({ genreIdOrCategoryName, page, searchQuery }) => {

        // * Get Movies by Search
        if(searchQuery) {
          return `search/movie?query=${searchQuery}&page=${page}&api_key=${tmdbApiKey}`
        }

        // * Get Movies by Category
        if (genreIdOrCategoryName && typeof genreIdOrCategoryName === "string") { // as category are populated by their names
          return `movie/${genreIdOrCategoryName}?page=${page}&api_key=${tmdbApiKey}`;
        }
        // * Get Movies by Genre
        if (genreIdOrCategoryName && typeof genreIdOrCategoryName === "number") { // as genres are populated by their id
          return `discover/movie?with_genres=${genreIdOrCategoryName}&page=${page}&api_key=${tmdbApiKey}`;
        }

        // * Get Popular Movies
        return `movie/popular?page=${page}&api_key=${tmdbApiKey}`
      },
    }),
  }),
});

export const {
  useGetGenresQuery,
  useGetMoviesQuery, // this hook is auto generated by rtk , so we can directly incorporate into another component by directly importing it
} = tmdbApi;
